### PR TITLE
Add Calculator component.

### PR DESCRIPTION
**Pull request by BenjaminSemah**
### In this project, I have worked on the following;
- Deleted all boilerplate from CRA,
- Created `components` directory,
- Created a `Calculator` component,
- Add style to the UI of the Calculator,
- Fixed all errors spotted by linters.

### CODE REVIEW

**Review by mikethreels — CHANGES_REQUESTED** [review]
Hi Benjamin, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
### I'm not able to leave inline comments for the below requirements that's why they are included in this comment.
- [x] The link to the license is not working as expected, please have a look at [the Microverse template](https://github.com/microverseinc/readme-template) to see how it is expected to work.
- [x] One of the requirements states that All the boilerplate that got created by the CRA (texts, images, and styles) ought to have gotten deleted. however, in the public folder, there are still a few files created by the CRA which can be deleted.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BenjaminSemah** [comment]
## Implemented Required Changes
#### I have implemented all changes pointed out by previous reviewer namely;
- Updated README to include correct link to MIT license,
- Deleted boilerplates files in public directory.

**Review by er-contreras — CHANGES_REQUESTED** [review]
Hi @BenjaminSemah, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

almost there

## Required Changes ♻️
- [ ] One of the suggestions from the last CR didn't apply(MIT LICENSE). Please add the necessary file to achieve this.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by elisha2kyakpo1 — APPROVED** [review]
Hi @BenjaminSemah, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
